version: '3'
services:
  postgres:
    image: "postgres"
    deploy:
      resources:
       limits:
         cpus: '1'
         memory: 500mb
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    ports:
      - "5432:5432"